### ISSUE TITLE
DoS ircdkit crashes if netcat touches it

### ISSUE THREAD

**Issue by kakolisgay** [Twipped/ircdkit#1] opened 2018-11-03 02:50 UTC
An example `ircdkit` server can be crashed by using netcat.

### leet haker
```bash
$ netcat localhost 6667
^C
$
```
### servar
```js
~/node_modules/ircdkit/lib/index.js:28
		if (client._socket) throw new Error('Cannot remove a connection with an active socket.');
		                    ^

Error: Cannot remove a connection with an active socket.
    at removeClient (~/node_modules/ircdkit/lib/index.js:28:29)
    at EventEmitter.<anonymous> (~/node_modules/ircdkit/lib/index.js:50:4)
    at emitOne (events.js:116:13)
    at EventEmitter.emit (events.js:211:7)
    at Socket.<anonymous> (~/node_modules/ircdkit/lib/connection.js:77:15)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
Is there a way to fix this?

**Comment by Twipped** [comment] 2018-11-03 18:33
Oh jeez, I dunno, I haven't looked a this code in 4 years.

**Comment by cottonflop** [comment] 2019-05-30 04:12
this is caused by an unhandled connection 'end' event, fixed by closing the connection before trying to remove it.

**Comment by Twipped** [comment] 2019-05-31 18:50
Published 1.0.4 with @cottonflop's fix.

**Closed by Twipped** 2019-05-31 18:50 UTC

**Comment by TestingPlant** [comment] 2021-01-30 07:21
On the advisory for [this](https://www.npmjs.com/advisories/735), it says that there is no fix available while, as far as I know, it was fixed by [this pull request](https://github.com/Twipped/ircdkit/pull/2). The advisory should be updated to note that it has been fixed in later versions, if possible.

**Comment by Twipped** [comment] 2021-02-10 21:49
@TestingPlant I didn't create that advisory, I have no idea how to change it. I don't even see any place on the package info page that shows it exists, let alone how to change it.
